"use client";

import Image from "next/image";
import Link from "next/link";
import { Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { useCart } from "@/context/CartContext";

export default function CartPage() {
  const { items, count, total, loading, error, updateQty, removeItem } = useCart();
  if (loading && !items.length) return <div className="min-h-screen px-6 pt-40 text-center">Loading your WooCommerce basket…</div>;
  if (!items.length) return <div className="min-h-screen bg-gray-50 px-6 pt-40 text-center"><ShoppingBag className="mx-auto text-gray-400" size={48} /><h1 className="mt-6 text-4xl font-semibold">Your basket is empty</h1><Link href="/shop" className="mt-8 inline-block bg-black px-7 py-4 text-xs font-bold uppercase tracking-[.2em] text-white">Browse products</Link></div>;
  return <div className="min-h-screen bg-gray-50 pb-20 pt-32"><div className="container-custom"><h1 className="py-10 text-4xl font-semibold">Basket ({count})</h1>{error && <p role="alert" className="mb-5 border border-red-200 bg-red-50 p-4 text-red-800">{error}</p>}<div className="grid gap-8 lg:grid-cols-[1fr_360px]"><div className="space-y-4">{items.map((item) => <article key={item.key} className="grid grid-cols-[80px_1fr] gap-5 border border-gray-200 bg-white p-5 sm:grid-cols-[96px_1fr_auto_auto] sm:items-center">{item.image ? <div className="relative aspect-square"><Image src={item.image} alt="" fill sizes="96px" className="object-contain" /></div> : <div className="aspect-square bg-gray-100" />}<div><Link href={`/product/${item.id}`} className="font-semibold">{item.name}</Link><p className="mt-1 text-sm text-gray-500">£{item.price.toFixed(2)} each</p></div><div className="flex items-center border border-gray-300"><button aria-label="Decrease quantity" onClick={() => updateQty(item.key, item.qty - 1)} className="p-3"><Minus size={14} /></button><span className="min-w-8 text-center">{item.qty}</span><button aria-label="Increase quantity" onClick={() => updateQty(item.key, item.qty + 1)} className="p-3"><Plus size={14} /></button></div><button aria-label={`Remove ${item.name}`} onClick={() => removeItem(item.key)} className="p-3 text-gray-500 hover:text-red-700"><Trash2 size={18} /></button></article>)}</div><aside className="h-fit border border-gray-200 bg-white p-7"><h2 className="text-xl font-semibold">Order summary</h2><div className="mt-6 flex justify-between border-t border-gray-200 pt-5"><span>Total</span><strong className="text-xl">£{total.toFixed(2)}</strong></div><p className="mt-2 text-xs text-gray-500">Shipping, discounts and tax are calculated by WooCommerce at checkout.</p><Link href="/checkout" className="mt-6 block bg-black px-6 py-4 text-center text-xs font-bold uppercase tracking-[.2em] text-white">Continue to checkout</Link></aside></div></div></div>;
}
