import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { env } from "@/config/env";
import { getBlogPostBySlug } from "@/lib/wordpress/posts";

interface Props { params: Promise<{ slug: string }> }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const post = await getBlogPostBySlug((await params).slug).catch(() => null); return post ? { title: post.title, description: post.excerpt, alternates: { canonical: `/blog/${post.slug}` }, openGraph: { type: "article", title: post.title, description: post.excerpt, publishedTime: post.date, images: post.featuredImage ? [post.featuredImage.url] : [] } } : { title: "Article not found" }; }
export default async function BlogPostPage({ params }: Props) { const post = await getBlogPostBySlug((await params).slug).catch(() => null); if (!post) notFound(); const schema = { "@context": "https://schema.org", "@type": "Article", headline: post.title, datePublished: post.date, dateModified: post.modified, author: { "@type": "Person", name: post.authorName }, mainEntityOfPage: `${env.siteUrl}/blog/${post.slug}`, image: post.featuredImage?.url }; return <article className="min-h-screen pb-20 pt-36"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} /><header className="container-custom max-w-4xl"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#a6549e]">{new Intl.DateTimeFormat("en-GB", { dateStyle: "long" }).format(new Date(post.date))}</p><h1 className="mt-5 text-4xl font-semibold leading-tight sm:text-6xl">{post.title}</h1><p className="mt-5 text-gray-600">By {post.authorName}</p>{post.featuredImage && <div className="relative mt-10 aspect-[16/9]"><Image src={post.featuredImage.url} alt={post.featuredImage.alt} fill priority className="object-cover" /></div>}</header><div className="prose prose-neutral container-custom mt-12 max-w-4xl" dangerouslySetInnerHTML={{ __html: post.content }} /></article>; }
