"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Search, ShoppingCart, UserRound, ClipboardList, Menu, X, ChevronDown, Truck, Star } from "lucide-react";
import { useCart } from "@/context/CartContext";
const links = ["Dermal Fillers", "Skin Boosters", "Consumables", "SPMU", "Training"];
type Result = { id: number; name: string; slug: string; price: string; image: string | null };
export default function Header() { const { count } = useCart(); const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const [results, setResults] = useState<Result[]>([]); const [searchOpen, setSearchOpen] = useState(false); const searchRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (query.trim().length < 2) { setResults([]); return; } const controller = new AbortController(); const timer = window.setTimeout(async () => { try { const response = await fetch(`/api/search?q=${encodeURIComponent(query)}`, { signal: controller.signal }); const data = await response.json(); setResults(data.items || []); setSearchOpen(true); } catch {} }, 250); return () => { window.clearTimeout(timer); controller.abort(); }; }, [query]);
  useEffect(() => { const close = (event: MouseEvent) => { if (!searchRef.current?.contains(event.target as Node)) setSearchOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []);
  return <header className="site-header"><div className="notice-bar"><div><Truck size={17} /> ORDER BEFORE 3PM FOR SAME-DAY DISPATCH <span>|</span> <UserRound size={17} /> UK AESTHETICS PROFESSIONALS</div><div className="notice-right"><span>SIGN IN / REGISTER</span><span><Star size={17} /> LOYALTY POINTS</span></div></div><div className="header-main container-custom"><Link href="/" className="brand"><img src="/logo.webp" alt="Destination Wholesale" /></Link><div className="search-wrap" ref={searchRef}><div className="search-box"><input value={query} onChange={(event) => { setQuery(event.target.value); setSearchOpen(true); }} onFocus={() => query.length > 1 && setSearchOpen(true)} placeholder="Search for products, brands or categories..." aria-label="Search products" /><Search size={22} /></div>{searchOpen && query.trim().length > 1 && <div className="search-results">{results.length ? results.map((product) => <Link key={product.id} href={`/product/${product.slug}`} onClick={() => setSearchOpen(false)}><span className="search-result-image">{product.image && <img src={product.image} alt="" />}</span><span><strong>{product.name}</strong><small>{product.price}</small></span></Link>) : <p>No products found</p>}</div>}</div><div className="header-actions"><Link href="/account"><UserRound /><small>My Account</small></Link><Link href="/shop"><ClipboardList /><small>Quick Order</small></Link><Link href="/cart" className="cart-action"><ShoppingCart /><b>{count}</b><small>Cart<br />£0.00</small></Link><button className="mobile-toggle" onClick={() => setOpen(!open)} aria-label="Menu">{open ? <X /> : <Menu />}</button></div></div><nav className={`category-nav ${open ? "open" : ""}`}><div className="container-custom"><div className="brand-menu"><Link href="/shop">BRANDS <ChevronDown size={14} /></Link><div className="brand-mega">{["Revolax", "Juvederm", "Teoxane", "Profhilo", "Aliaxin", "Mastelli", "Ami", "Stylage"].map((brand) => <Link key={brand} href={`/shop?brand=${encodeURIComponent(brand)}`}>{brand}</Link>)}</div></div>{links.map((label) => <Link key={label} href="/shop">{label}<ChevronDown size={14} /></Link>)}<Link href="/shop" className="sale-link">SALE</Link></div></nav></header>;
}
