import type { Metadata } from "next";
import Link from "next/link";
import ProductCard from "@/components/products/ProductCard";
import { getCategories, getProducts, getBrands } from "@/lib/woocommerce/products";
export const metadata: Metadata = { title: "Shop professional supplies" };
const value = (input: string | string[] | undefined) => Array.isArray(input) ? input[0] : input;
export default async function ShopPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams; const page = Math.max(1, Number(value(params.page) || 1)); const category = value(params.category); const search = value(params.search); const brand = value(params.brand); const minPrice = Number(value(params.minPrice) || 0) || undefined; const maxPrice = Number(value(params.maxPrice) || 0) || undefined; const sort = value(params.sort) || "date-desc"; const [orderBy, order] = sort.split("-") as ["date" | "price" | "popularity" | "rating", "asc" | "desc"];
  const [products, categories, brands] = await Promise.all([getProducts({ page, perPage: 24, category, search: brand ? `${brand} ${search || ""}` : search, orderBy, order, minPrice, maxPrice }).catch(() => ({ items: [], total: 0, totalPages: 0, page })), getCategories().catch(() => []), getBrands().catch(() => [])]);
  const queryFor = (nextPage: number) => { const next = new URLSearchParams(); [["category", category], ["search", search], ["brand", brand], ["minPrice", minPrice], ["maxPrice", maxPrice], ["sort", sort], ["page", nextPage]].forEach(([key, val]) => { if (val) next.set(String(key), String(val)); }); return `/shop?${next}`; };
  return <div className="shop-page min-h-screen bg-white pb-20 pt-32"><header className="shop-hero"><div className="container-custom py-8"><nav className="text-sm text-gray-600"><Link href="/">Home</Link> &gt; Shop</nav><h1 className="mt-1 text-5xl font-semibold">Shop</h1><p className="mt-2">Explore our professional aesthetics range.</p></div></header><div className="container-custom py-10"><form className="shop-toolbar grid gap-3 border border-gray-200 bg-white p-4 md:grid-cols-[1fr_180px_auto]" action="/shop"><input name="search" defaultValue={search} placeholder="Search products or SKU" className="border border-gray-300 px-4 py-3" /><select name="sort" defaultValue={sort} className="border border-gray-300 px-4 py-3"><option value="date-desc">Newest</option><option value="popularity-desc">Popular</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option></select><button className="bg-black px-6 py-3 text-xs font-bold uppercase text-white">Apply</button></form><div className="shop-layout"><aside className="shop-sidebar"><h3>CATEGORIES</h3>{categories.map((item) => <Link key={item.id} href={`/shop?category=${item.id}`}>{item.name}<span>({item.count})</span></Link>)}<form action="/shop" className="sidebar-filter"><input type="hidden" name="search" value={search || ""} />{category && <input type="hidden" name="category" value={category} />}<h3 className="sidebar-subtitle">FILTER BY PRICE</h3><div className="price-fields"><input name="minPrice" defaultValue={minPrice || ""} type="number" min="0" placeholder="Min £" /><input name="maxPrice" defaultValue={maxPrice || ""} type="number" min="0" placeholder="Max £" /></div><h3 className="sidebar-subtitle">BRANDS</h3>{brands.map((item) => <label key={item.slug} className="sidebar-brand"><input type="radio" name="brand" value={item.name} defaultChecked={brand === item.name} /> {item.name}</label>)}<button className="sidebar-apply">Apply filters</button></form></aside><div className="shop-results"><div className="mt-8 flex justify-between text-sm text-gray-600"><span>{products.total} products</span>{search && <span>Results for “{search}”</span>}</div>{!products.items.length ? <div className="mt-8 border p-12 text-center"><h2 className="text-2xl font-semibold">No products found</h2></div> : <div className="mt-8 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.items.map((product) => <ProductCard key={product.id} product={product} />)}</div>}{products.totalPages > 1 && <nav className="mt-12 flex justify-center gap-3">{page > 1 && <Link className="border px-5 py-3" href={queryFor(page - 1)}>Previous</Link>}<span className="px-5 py-3">Page {page} of {products.totalPages}</span>{page < products.totalPages && <Link className="border px-5 py-3" href={queryFor(page + 1)}>Next</Link>}</nav>}</div></div></div></div>;
}
