"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { UserRound } from "lucide-react";

export default function AccountPage() {
  const [mode, setMode] = useState<"login" | "register">("login");
  const [submitted, setSubmitted] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true); };
  return <main className="account-page min-h-screen bg-[#F9F7FB] px-4 pb-20 pt-12 sm:px-6 sm:pt-16"><div className="mx-auto max-w-lg border border-[#E8E4EB] bg-white p-6 sm:p-10"><div className="text-center"><UserRound className="mx-auto text-[#6B1FAD]" size={32} /><p className="mt-4 text-xs font-bold uppercase tracking-[.25em] text-[#B174E7]">Destination Wholesale</p><h1 className="mt-2 text-3xl font-semibold text-[#2D2633]">{mode === "login" ? "Welcome back" : "Create your account"}</h1></div><div className="mt-8 grid grid-cols-2 border-b border-[#E8E4EB]"><button type="button" onClick={() => { setMode("login"); setSubmitted(false); }} className={`border-b-2 px-4 py-3 text-sm font-semibold ${mode === "login" ? "border-[#9440DD] text-[#6B1FAD]" : "border-transparent text-[#6B6570]"}`}>Log in</button><button type="button" onClick={() => { setMode("register"); setSubmitted(false); }} className={`border-b-2 px-4 py-3 text-sm font-semibold ${mode === "register" ? "border-[#9440DD] text-[#6B1FAD]" : "border-transparent text-[#6B6570]"}`}>Sign up</button></div>{submitted ? <div className="mt-8 border border-[#CEA8F0] bg-[#F9F7FB] p-5 text-sm text-[#2D2633]">Thanks. Your request has been captured and will be connected to the WooCommerce customer account service.</div> : <form onSubmit={submit} className="mt-8 space-y-4"><label className="block text-sm font-medium text-[#2D2633]">Email address<input required type="email" className="mt-2 h-12 w-full border border-[#E8E4EB] px-4" /></label>{mode === "register" && <label className="block text-sm font-medium text-[#2D2633]">Full name<input required className="mt-2 h-12 w-full border border-[#E8E4EB] px-4" /></label>}<label className="block text-sm font-medium text-[#2D2633]">Password<input required type="password" className="mt-2 h-12 w-full border border-[#E8E4EB] px-4" /></label><button className="h-12 w-full bg-[#1CABB0] px-6 font-semibold text-white hover:bg-[#178E93]">{mode === "login" ? "Log in" : "Create account"}</button>{mode === "login" && <Link href="/order-tracking" className="block text-center text-sm text-[#6B1FAD]">Track an order instead</Link>}</form>}</div></main>;
}
